### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by rahulkapoor90**
Added meta social tags and stylesheets in a folder.

### CODE REVIEW

**Comment by avinassh** [comment]
I forgot to reply, my apologizes. Can you explain why this PR?

**Comment by rahulkapoor90** [comment]
Meta tags improve's saveourcinema's social presence currently there are commented i think and css files are added to stylesheets folder to remove clutter.

**Comment by avinassh** [comment]
tbh I find its not really necessary. Sorry, closing this!

**Comment by rahulkapoor90** [comment]
:+1:

**Pull request closed without merging**
